from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

from deerflow.skills.catalog import SkillCatalog


class PlanStepKind(StrEnum):
    """Kind of step in an execution plan."""

    sequence = "sequence"
    parallel = "parallel"
    gate = "gate"


@dataclass
class ExecutionStep:
    """A single step in an execution plan.

    Attributes:
        skill: Skill name to execute. Empty for gate/parallel steps.
        channel: Channel/blueprint to use (e.g. ``"full"``, ``"analysis"``).
        description: Human-readable description of this step.
        kind: Step kind (sequence, parallel, gate).
        params: Optional parameters for the step.
    """

    skill: str
    channel: str = "standard"
    description: str = ""
    kind: PlanStepKind = PlanStepKind.sequence
    params: dict[str, Any] = field(default_factory=dict)

    @property
    def is_gate(self) -> bool:
        return self.kind == PlanStepKind.gate

    @staticmethod
    def gate(description: str = "Human review required") -> ExecutionStep:
        return ExecutionStep(
            skill="",
            channel="",
            description=description,
            kind=PlanStepKind.gate,
        )

    @staticmethod
    def parallel(description: str = "Parallel execution", steps: list[ExecutionStep] | None = None) -> ExecutionStep:
        return ExecutionStep(
            skill="",
            channel="",
            description=description,
            kind=PlanStepKind.parallel,
            params={"steps": steps or []},
        )


@dataclass
class ExecutionPlan:
    """An ordered list of execution steps generated by the orchestrator.

    Attributes:
        steps: Ordered list of execution steps.
        metadata: Optional metadata about the plan (confidence, reasoning, etc.).
    """

    steps: list[ExecutionStep]
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def total_steps(self) -> int:
        return len(self.steps)

    def has_next(self, index: int) -> bool:
        return index < self.total_steps - 1


# ---------------------------------------------------------------------------
# Keyword → skill/ channel mapping (extended from classifier.py)
# ---------------------------------------------------------------------------

_SKILL_MAP: list[tuple[str, str, list[str]]] = [
    # (skill, channel, keywords)
    ("deep-research", "full", ["调研", "研究", "research", "论文", "文献", "survey", "sota"]),
    ("deep-research", "quick", ["查", "搜索", "search", "find", "look up", "what is"]),
    ("data-analysis", "full", ["分析", "分析数据", "数据分析", "可视化", "数据趋势", "统计", "analysis"]),
    ("data-analysis", "quick", ["图表", "chart", "plot", "简单统计"]),
    ("code-documentation", "full", ["文档", "documentation", "docstring", "readme", "api文档", "设计", "design"]),
    ("image-generation", "standard", ["生成图片", "生成图像", "图片", "图像", "image", "draw"]),
    ("podcast-generation", "standard", ["播客", "podcast", "音频", "audio"]),
]

_CHANNEL_WEIGHTS: dict[str, int] = {
    "quick": 0,
    "lite": 1,
    "standard": 2,
    "full": 3,
    "analysis": 3,
    "planning": 3,
}

# Task complexity keywords → suggested channel depth
_COMPLEXITY_KEYWORDS: dict[str, list[str]] = {
    "full": [
        "实现", "构建", "开发", "完整", "系统", "架构", "设计",
        "implement", "build", "develop", "complete", "system", "architecture",
    ],
    "analysis": [
        "分析", "调研", "评估", "对比", "研究", "深度",
        "analysis", "research", "evaluate", "compare", "deep",
    ],
    "planning": [
        "规划", "方案", "路线图", "计划",
        "plan", "roadmap", "strategy", "proposal",
    ],
}

_STANDARD_KEYWORDS = ["修复", "修改", "添加", "fix", "add", "update", "change", "refactor"]


def _score_channel(description: str) -> str:
    """Determine the appropriate channel depth from task description."""
    desc_lower = description.lower()
    for channel, keywords in _COMPLEXITY_KEYWORDS.items():
        if any(kw in desc_lower for kw in keywords):
            return channel
    if any(kw in desc_lower for kw in _STANDARD_KEYWORDS):
        return "standard"
    return "lite"


def _match_skills(description: str, catalog: SkillCatalog) -> list[tuple[str, str, float]]:
    """Match task description to skills in the catalog.

    Returns list of (skill_name, channel, score) sorted by score descending.
    """
    desc_lower = description.lower()
    fallback_channel = _score_channel(description)
    scored: list[tuple[str, str, float]] = []

    for skill in catalog.skills:
        score = 0.0
        matched_channel = fallback_channel
        best_channel_keywords = 0

        # Check keyword map — track which channel has the most keyword hits
        for s_name, s_ch, keywords in _SKILL_MAP:
            if s_name != skill.name:
                continue
            kw_hits = sum(1 for kw in keywords if kw in desc_lower)
            if kw_hits > 0:
                score += kw_hits * 0.3
                if kw_hits > best_channel_keywords:
                    best_channel_keywords = kw_hits
                    matched_channel = s_ch

        # Check skill description word overlap
        desc_words = set(desc_lower.split())
        skill_desc_words = set(skill.description.lower().split())
        overlap = desc_words & skill_desc_words
        score += len(overlap) * 0.1

        # Check skill name in description
        if skill.name.lower().replace("-", " ") in desc_lower:
            score += 0.5

        # Fallback: small score from description overlap even without keywords
        if score == 0 and len(overlap) > 0:
            score = 0.05  # minimal match via description

        if score > 0:
            scored.append((skill.name, matched_channel, min(score, 1.0)))

    scored.sort(key=lambda x: x[2], reverse=True)
    return scored


def _build_plan(
    matches: list[tuple[str, str, float]],
    description: str,
    human_review: bool,
) -> ExecutionPlan:
    """Build an ExecutionPlan from matched skills."""
    steps: list[ExecutionStep] = []
    metadata = {
        "total_matches": len(matches),
        "top_skill": matches[0][0] if matches else None,
        "top_confidence": matches[0][2] if matches else 0.0,
    }

    if not matches:
        return ExecutionPlan(steps=[], metadata=metadata)

    # Primary skill
    primary_skill, primary_channel, _ = matches[0]
    steps.append(ExecutionStep(
        skill=primary_skill,
        channel=primary_channel,
        description=f"Execute {primary_skill} ({primary_channel})",
    ))

    # Gate for complex tasks with human_review
    if human_review:
        steps.append(ExecutionStep.gate("Human review before proceeding"))

    # Secondary skills (complementary)
    for skill_name, skill_channel, _ in matches[1:3]:
        steps.append(ExecutionStep(
            skill=skill_name,
            channel=skill_channel,
            description=f"Complementary: {skill_name} ({skill_channel})",
        ))

    return ExecutionPlan(steps=steps, metadata=metadata)


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------


class SkillOrchestrator:
    """Generates execution plans by matching tasks to available skills.

    Uses the SkillCatalog to discover available skills and matches
    task descriptions using a combination of keyword matching and
    semantic overlap with skill descriptions.
    """

    def plan(
        self,
        description: str,
        catalog: SkillCatalog,
        human_review: bool = False,
    ) -> ExecutionPlan:
        """Generate an execution plan for a task description.

        Args:
            description: Natural language task description.
            catalog: SkillCatalog with available skills.
            human_review: If True, insert gate steps for human approval.

        Returns:
            An ExecutionPlan with ordered steps.
        """
        if not catalog.skills:
            return ExecutionPlan(steps=[])

        matches = _match_skills(description, catalog)
        return _build_plan(matches, description, human_review)
